### ISSUE TITLE
Finding a friend's subfeed

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-meta-feeds#79]
> Add a find method to be able to find "my friends helsinki feed"

cc @mixmix 

I think this could be achieved with `branchStream`, although branch stream is going to return all the intermediate branches, like

- `root`
- `root-->v1`
- `root-->v1-->7`
- `root-->v1-->7-->chess`
- `root-->v1-->7-->gatherings`

And we might need a simpler API that allows us to just get:

- `chess`
- `gatherings`

MAYBE. Because we might also need the friend's root metafeed (say we need to calculate the shard feed for their helsinki group feed, and to calculate shards we need to know the root MF ID).

**Comment by arj03** [comment]
Isn't this triangulate?

**Comment by staltz** [comment]
Yes I think we could close this issue. `getTree` has been pretty useful: https://github.com/ssbc/ssb-box2/blob/40399820ad007e058594eaf0e18633a5813d83cd/monitor.js#L66
