### ISSUE TITLE
Clarify findByIdSync

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-meta-feeds#80]
When reading the docs

> sbot.metafeeds.findByIdSync(feedId)
>
> Similar to findById, but returns synchronously. warning Note, in order to use this API, you must call sbot.metafeeds.loadState(cb) first, and wait for cb to be called.

It's a bit unclear if I just have to had called loadState at some point, or if i have to call it immediately before findByIdSync, every time.

**Comment by staltz** [comment]
I think we can remove this from readme because the functions were also deleted, is I remember correctly
